# Generated by Django 2.1.7 on 2019-04-06 11:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Name')),
                ('slug', slugger.fields.AutoSlugField(null=True, populate_from='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(blank=True, max_length=200)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('text_eng', ckeditor.fields.RichTextField(blank=True)),
                ('accords', ckeditor.fields.RichTextField(blank=True)),
                ('presentation', models.FileField(blank=True, upload_to='presentations/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Category')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song'),
        ),
    ]
