# Generated by Django 2.0.6 on 2018-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_text',
        ),
        migrations.AddField(
            model_name='song',
            name='accords',
            field=models.FileField(blank=True, upload_to='accords/'),
        ),
        migrations.AddField(
            model_name='song',
            name='presentation',
            field=models.FileField(blank=True, upload_to='presentations/'),
        ),
        migrations.AddField(
            model_name='song',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='urls',
            field=models.URLField(blank=True),
        ),
    ]
