# Generated by Django 2.0.6 on 2018-08-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180816_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title_eng',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
