# Generated by Django 2.0.6 on 2018-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20180817_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='eng',
            new_name='text_eng',
        ),
        migrations.AlterField(
            model_name='song',
            name='accords',
            field=models.TextField(blank=True),
        ),
    ]
