# Generated by Django 2.0.6 on 2018-08-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20180817_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, choices=[('all', 'Основные'), ('child', 'Детские'), ('christmas', 'Рождественские')], default='all', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Category'),
        ),
    ]
