# Generated by Django 2.0.6 on 2018-08-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20180821_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='song.Category'),
        ),
    ]
