# Generated by Django 2.0.6 on 2018-09-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_auto_20180821_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='choice',
            field=models.CharField(blank=True, choices=[('Основные', 'Основные'), ('Детские', 'Детские'), ('Рождественские', 'Рождественские'), ('Пасхальные', 'Пасхальные')], default='Основные', max_length=20),
        ),
    ]
