# Generated by Django 2.0.6 on 2018-10-26 15:09

from django.db import migrations, models
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_auto_20180925_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=slugger.fields.AutoSlugField(null=True, populate_from='name'),
        ),
    ]
