# Generated by Django 2.0.6 on 2018-10-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_auto_20181026_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='choice',
        ),
    ]
