# Generated by Django 2.0.6 on 2018-11-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0011_remove_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=200, null='True'),
        ),
    ]
