# Generated by Django 2.0.6 on 2018-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0012_auto_20181108_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='presentation',
            field=models.FileField(blank=True, upload_to='static/presentations/'),
        ),
    ]
