# Generated by Django 2.0.6 on 2018-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0013_auto_20181207_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='presentation',
            field=models.FileField(blank=True, upload_to='media/presentations/'),
        ),
    ]
