# Generated by Django 2.0.6 on 2018-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0014_auto_20181210_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='presentation',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
