# Generated by Django 2.0.6 on 2019-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0017_auto_20181223_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='accords',
            field=models.TextField(blank=True),
        ),
    ]
