# Generated by Django 2.0.6 on 2019-03-07 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0018_auto_20190302_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='accords',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
