# Generated by Django 2.2.3 on 2019-07-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worship', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
