# Generated by Django 2.2.10 on 2020-02-04 12:53

import ckeditor.fields
import django.db.models.deletion
import django_extensions.db.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('slug', models.CharField(default='', max_length=10)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='categs/')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_eng', models.CharField(blank=True, max_length=255)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('text_eng', ckeditor.fields.RichTextField(blank=True)),
                ('chords', ckeditor.fields.RichTextField(blank=True)),
                ('presentation', models.FileField(blank=True, upload_to='presentations/')),
                ('text_file', models.FileField(blank=True, upload_to='text/')),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('is_translated', models.BooleanField(blank=True, default=True)),
                ('main_key', models.CharField(blank=True, choices=[('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('A', 'A'), ('A#', 'A#'), ('B', 'B')], default='E', max_length=2)),
                ('difficult', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6)),
                ('category', models.ManyToManyField(blank=True, to='songs.Category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('ytb_id', models.CharField(blank=True, help_text='Youtube ID for video embedding', max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_links', to='songs.Song')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('chords', models.FileField(blank=True, upload_to='chords/')),
                ('key', models.CharField(blank=True, choices=[('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('A', 'A'), ('A#', 'A#'), ('B', 'B')], default='E', max_length=2)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_files', to='songs.Song')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
