# Generated by Django 2.2.13 on 2020-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200204_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='chordKey1',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='song',
            name='chordKey2',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='song',
            name='chordsFile1',
            field=models.FileField(blank=True, upload_to='chords/'),
        ),
        migrations.AddField(
            model_name='song',
            name='chordsFile2',
            field=models.FileField(blank=True, upload_to='chords/'),
        ),
        migrations.AddField(
            model_name='song',
            name='ytb_id1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='ytb_id2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='ytb_id3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Chord',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
