# Generated by Django 2.2.5 on 2019-11-26 11:11

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20191126_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='is_translated',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Детские, Общие, Пасхальные, Рождественские', max_count=4, to='songs.Tagulous_Song_category'),
        ),
        migrations.CreateModel(
            name='Tagulous_Song_translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='song',
            name='translator',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Зуев, Иваник, Куга, Фурманов', max_count=4, to='songs.Tagulous_Song_translator'),
        ),
    ]
