# Generated by Django 2.2.5 on 2020-01-20 12:29

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20191126_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='accords_dwnl',
            field=models.FileField(blank=True, upload_to='accords/'),
        ),
        migrations.AddField(
            model_name='song',
            name='text_dwnl',
            field=models.FileField(blank=True, upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Детские, Общие, Пасхальные, Рождественские', max_count=4, to='songs.Tagulous_Song_category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='translator',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Герсимович, Жданов, Зуев, Иваник, Куга, Фурманов', max_count=0, to='songs.Tagulous_Song_translator'),
        ),
    ]
