# Generated by Django 2.2.5 on 2020-01-26 14:45

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20191126_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='accords_dwnl',
            field=models.FileField(blank=True, upload_to='accords/'),
        ),
        migrations.AddField(
            model_name='song',
            name='text_dwnl',
            field=models.FileField(blank=True, upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Детские, Общие, Пасхальные, Рождественские', max_count=4, to='songs.Tagulous_Song_category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='translator',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Герсимович, Жданов, Зуев, Иваник, Куга, Фурманов', max_count=6, to='songs.Tagulous_Song_translator'),
        ),
        migrations.CreateModel(
            name='Tagulous_Song_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null='True')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='A, C, D, D, E, F, G', max_count=4, to='songs.Tagulous_Song_key'),
        ),
    ]
