# Generated by Django 2.2.5 on 2020-01-26 14:58

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200126_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='accords_dwnl2',
            field=models.FileField(blank=True, upload_to='accords/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Детские, Общие, Пасхальные, Рождественские', max_count=4, to='songs.Tagulous_Song_category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='A, C, D, D, E, F, G', max_count=3, to='songs.Tagulous_Song_key'),
        ),
        migrations.AlterField(
            model_name='song',
            name='translator',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='Герсимович, Жданов, Зуев, Иваник, Куга, Фурманов', max_count=6, to='songs.Tagulous_Song_translator'),
        ),
    ]
